title: Julius Wons
#logo: /files/img/headshot_small.png
  
description: <a href="https://www.linkedin.com/in/julius-wons/">LinkedIn </a> | <a href="https://github.com/jcwons">GitHub</a> <br><br> I'm a physicist specialising in modelling and optimising methods. I received my PhD in theoretical physics from UNSW Sydney for developing Machine Learning algorithms for cosmological data. I enjoy bringing my ideas to "life" by modelling all kinds of processes.


#show_downloads: true

remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
