title: Julius Wons
logo: /files/img/headshot_round.jpg
description: 
<a href="https://www.linkedin.com/in/julius-wons/">LinkedIn </a>

I am a curious scientist with 5 years of experience in data analysis and data modelling. I recently obtained my PhD in Physics from UNSW for developing Machine Learning algorithms for cosmological data. I enjoy playing around with data and using the newest machine-learning algorithms.
#show_downloads: true
theme: jekyll-theme-minimal
