title: Julius Wons
logo:
  image: /files/img/headshot_round.jpg
  width: 100 
  height: 100
  
description: <a href="https://www.linkedin.com/in/julius-wons/">LinkedIn </a> | <a href="https://github.com/jcwons">GitHub</a> <br><br> I'm a curious scientist with 5 years of experience in data analysis and data modelling. I recently obtained my PhD in Physics from UNSW for developing Machine Learning algorithms for cosmological data. I enjoy playing around with data and using the newest machine-learning algorithms.


#show_downloads: true

remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
